name: copia
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  moor_flutter: ^3.0.0
  provider: ^4.0.5+1
  majesty: ^0.0.1
  flutter_pdfview: ^1.0.1
  path_provider: ^1.6.7
  qr_flutter: ^3.2.0
  google_fonts: ^1.0.0
  skeleton_text: ^1.0.0
  image_picker: ^0.6.5+3
  json_annotation: ^3.0.1
  flutter_svg: ^0.17.4
  file_picker: ^1.9.0+1

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  moor_generator:
  build_runner:
  json_serializable: ^3.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/magazine.pdf
    - assets/maths.pdf
    - assets/images/
    
