name: copia
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0 
  path_provider: ^2.0.2
  flutter_svg: ^0.21.0+1
  file_picker: ^4.0.2
  fab_circular_menu: ^1.0.0
  hive_flutter: ^1.1.0
  hive: ^2.0.4
  native_pdf_view: ^4.0.1
  shared_preferences: ^0.5.7+1
  image_gallery_saver: ^1.2.2
  flutter_sound: ^8.3.11
  flutter_spinkit: ^5.0.0
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^1.1.8+4
  flat_icons_flutter: ^1.0.2 
  intl: ^0.17.0
  permission_handler: ^8.1.4+2
  flutter_share: ^2.0.0
  open_file: ^3.0.1
  fl_chart: ^0.35.0
  flip_card: ^0.5.0
  font_awesome_flutter: ^9.0.0
  animate_do: ^2.0.0
  # assets_audio_player: ^3.0.3+2


flutter_icons:
  android: "launcher_icon"
  ios: true
  macos: true 
  image_path: "assets/images/logo/owl.png"

flutter_native_splash:
  image: assets/images/logo/copia.png
  color: "26292D"
  fill: true

  cupertino_icons: ^0.1.3

dev_dependencies:
  build_runner:
  hive_generator: ^1.1.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/images/IntroImages/

  fonts:
    - family: owl
      fonts:
        - asset: assets/Fonts/Owl.ttf
    - family: cormorant
      fonts:
        - asset: assets/Fonts/cormorant.ttf