name: copia
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.0.5+1
  path_provider: ^1.6.7
  google_fonts: ^1.0.0
  image_picker: ^0.6.5+3
  flutter_svg: ^0.17.4
  file_picker: ^1.9.0+1
  fab_circular_menu: ^1.0.0
  hive_flutter: ^0.3.0+2
  hive: ^1.4.1+1
  native_pdf_view: ^3.6.2
  shared_preferences: ^0.5.7+1
  image_gallery_saver: ^1.2.2
  flutter_sound: ^4.0.4+1
  pdf_text: ^0.2.1
  flutter_spinkit: ^4.1.2+1
  flutter_launcher_icons: ^0.7.5
  flutter_native_splash: ^0.1.9
  flat_icons_flutter: ^1.0.2 
  intl: ^0.16.1
  permission_handler: ^5.0.0+hotfix.6
  esys_flutter_share: ^1.0.2
  flutter_share: ^1.0.2+1
  open_file: ^3.0.1
  fl_chart: ^0.9.4
  flip_card: ^0.4.4
  font_awesome_flutter: ^8.8.1
  neumorphic: ^0.3.0
  flutter_neumorphic: ^3.0.1
  animate_do: ^1.7.2






flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo/owl.png"

flutter_native_splash:
  image: assets/images/logo/copia.png
  color: "26292D"
  fill: true

  cupertino_icons: ^0.1.3

dev_dependencies:
  build_runner:
  hive_generator: ^0.7.0+2

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/images/IntroImages/

  fonts:
    - family: owl
      fonts:
        - asset: assets/Fonts/Owl.ttf
    - family: cormorant
      fonts:
        - asset: assets/Fonts/cormorant.ttf