name: copia
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.0.5+1
  majesty: ^0.0.3
  path_provider: ^1.6.7
  qr_flutter: ^3.2.0
  google_fonts: ^1.0.0
  skeleton_text: ^1.0.0
  image_picker: ^0.6.5+3
  json_annotation: ^3.0.1
  flutter_svg: ^0.17.4
  file_picker: ^1.9.0+1
  fab_circular_menu: ^1.0.0
  hive_flutter: ^0.3.0+2
  hive: ^1.4.1+1
  native_pdf_view: ^3.1.0
  shared_preferences: ^0.5.7+1

  cupertino_icons: ^0.1.3

dev_dependencies:
  moor_generator:
  build_runner:
  hive_generator: ^0.7.0+2

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: cormorant
      fonts:
        - asset: assets/Fonts/cormorant.ttf
